import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { useTheme } from '../context/ThemeContext';
import { 
  Sparkles, 
  Building, 
  MapPin, 
  AlertTriangle, 
  Globe, 
  Search, 
  Megaphone, 
  TrendingUp, 
  Printer, 
  Share2, 
  ArrowLeft, 
  CheckCircle2, 
  MessageSquare,
  Copy,
  Check,
  RefreshCw
} from 'lucide-react';

export default function Report() {
  const location = useLocation();
  const navigate = useNavigate();
  const { theme } = useTheme();
  const isDark = theme === 'dark';

  const [reportData, setReportData] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (location.state?.report) {
      setReportData(location.state);
    } else {
      const stored = localStorage.getItem('ai_growth_report');
      if (stored) {
        try {
          setReportData(JSON.parse(stored));
        } catch (e) {
          console.error('Failed to parse stored report', e);
        }
      }
    }
  }, [location.state]);

  if (!reportData || !reportData.report) {
    return (
      <div className={`min-h-screen pt-32 pb-20 flex items-center justify-center px-4 transition-colors duration-300 ${
        isDark ? 'bg-slate-950 text-white' : 'bg-slate-50 text-slate-900'
      }`}>
        <div className={`max-w-md w-full border rounded-3xl p-8 text-center space-y-6 shadow-2xl ${
          isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'
        }`}>
          <div className="w-16 h-16 rounded-2xl bg-indigo-500/10 text-indigo-500 flex items-center justify-center mx-auto border border-indigo-500/20">
            <Sparkles className="w-8 h-8 text-indigo-500 animate-pulse" />
          </div>
          <div className="space-y-2">
            <h2 className={`text-2xl font-bold ${isDark ? 'text-white' : 'text-slate-900'}`}>No Growth Report Found</h2>
            <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>
              Please submit your business details first to let Gemini AI generate a personalized growth strategy report.
            </p>
          </div>
          <Link
            to="/analysis"
            className="inline-flex items-center justify-center gap-2 w-full px-6 py-3 rounded-xl bg-gradient-to-r from-indigo-600 to-cyan-500 text-white font-bold text-sm shadow-lg shadow-indigo-600/30 hover:opacity-95 transition-all"
          >
            Start Business Analysis
          </Link>
        </div>
      </div>
    );
  }

  const { report, businessDetails } = reportData;

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    const textToCopy = `AI DIGITAL GROWTH REPORT FOR ${businessDetails?.businessName || 'Business'}
Category: ${businessDetails?.businessCategory || 'N/A'} | Location: ${businessDetails?.location || 'N/A'}
Score: ${report.score || 85}/100

EXECUTIVE OVERVIEW:
${report.summary || 'Custom business strategy generated by AI.'}

IDENTIFIED PROBLEMS:
${report.problems?.map(p => `- ${p.issue}: ${p.explanation}`).join('\n') || 'N/A'}

WEBSITE SUGGESTIONS:
${report.websiteSuggestions?.map(w => `- ${w}`).join('\n') || 'N/A'}

SEO STRATEGY:
${report.seoStrategy?.map(s => `- ${s.tactic}: ${s.details}`).join('\n') || 'N/A'}

MARKETING PLAN:
${report.marketingPlan?.map(m => `- ${m.channel}: ${m.strategy} (ROI: ${m.expectedRoi})`).join('\n') || 'N/A'}

GROWTH RECOMMENDATIONS:
${report.growthRecommendations?.map(r => `- ${r}`).join('\n') || 'N/A'}`;

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const whatsappMessage = encodeURIComponent(
    `Hi! I generated an AI Digital Growth Report for my business "${businessDetails?.businessName || 'My Business'}" on your platform. I'd like to discuss implementing the website, SEO, and marketing roadmap!`
  );

  return (
    <div className={`min-h-screen pt-28 pb-20 transition-colors duration-300 print:bg-white print:text-slate-900 print:pt-0 print:pb-0 ${
      isDark ? 'bg-slate-950 text-white' : 'bg-slate-50 text-slate-900'
    }`}>
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
        
        {/* Top Control Bar (Hidden on print) */}
        <div className="flex flex-wrap items-center justify-between gap-4 print:hidden">
          <button
            onClick={() => navigate('/analysis')}
            className={`inline-flex items-center gap-2 text-sm font-medium transition-colors ${
              isDark ? 'text-slate-400 hover:text-white' : 'text-slate-600 hover:text-indigo-600'
            }`}
          >
            <ArrowLeft className="w-4 h-4" /> Back to Analysis Form
          </button>

          <div className="flex items-center gap-3">
            <button
              onClick={handleCopy}
              className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl border text-xs font-semibold transition-all ${
                isDark ? 'bg-slate-900 border-slate-800 text-slate-300 hover:bg-slate-800' : 'bg-white border-slate-300 text-slate-700 hover:bg-slate-100 shadow-sm'
              }`}
            >
              {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4 text-indigo-500" />}
              {copied ? 'Copied!' : 'Copy Text'}
            </button>
            <button
              onClick={handlePrint}
              className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl border text-xs font-semibold transition-all ${
                isDark ? 'bg-slate-900 border-slate-800 text-slate-300 hover:bg-slate-800' : 'bg-white border-slate-300 text-slate-700 hover:bg-slate-100 shadow-sm'
              }`}
            >
              <Printer className="w-4 h-4 text-cyan-500" />
              Print / Save PDF
            </button>
            <a
              href={`https://wa.me/919876543210?text=${whatsappMessage}`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-[#25D366] hover:bg-[#20ba5a] text-white text-xs font-bold transition-all shadow-md shadow-emerald-600/20"
            >
              <Share2 className="w-4 h-4" />
              Share on WhatsApp
            </a>
          </div>
        </div>

        {/* MAIN REPORT CARD */}
        <div className={`border rounded-3xl p-6 sm:p-10 space-y-10 shadow-2xl print:bg-white print:border-none print:shadow-none transition-colors ${
          isDark ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200 shadow-slate-200/50'
        }`}>
          
          {/* Header & Business Score Banner */}
          <div className={`border-b pb-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 ${
            isDark ? 'border-slate-800' : 'border-slate-200'
          }`}>
            <div className="space-y-2">
              <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full border text-xs font-bold uppercase tracking-wider ${
                isDark ? 'bg-indigo-500/10 border-indigo-500/20 text-indigo-300' : 'bg-indigo-50 border-indigo-200 text-indigo-700'
              }`}>
                <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
                Gemini AI Digital Strategy Audit
              </div>
              <h1 className={`text-3xl sm:text-4xl font-extrabold tracking-tight ${
                isDark ? 'text-white' : 'text-slate-900'
              }`}>
                {businessDetails?.businessName || 'Business Audit Report'}
              </h1>
              <div className={`flex flex-wrap items-center gap-x-4 gap-y-1 text-sm ${
                isDark ? 'text-slate-400' : 'text-slate-600'
              }`}>
                <span className="flex items-center gap-1">
                  <Building className="w-4 h-4 text-indigo-500" />
                  {businessDetails?.businessCategory || 'General Category'}
                </span>
                <span>•</span>
                <span className="flex items-center gap-1">
                  <MapPin className="w-4 h-4 text-cyan-500" />
                  {businessDetails?.location || 'Local Market'}
                </span>
                <span>•</span>
                <span>Owner: <strong className={isDark ? 'text-slate-200' : 'text-slate-800'}>{businessDetails?.ownerName || 'N/A'}</strong></span>
              </div>
            </div>

            {/* Score Box */}
            <div className={`p-5 rounded-2xl border text-center min-w-[150px] shrink-0 ${
              isDark ? 'bg-slate-950 border-slate-800' : 'bg-slate-50 border-slate-200'
            }`}>
              <span className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-emerald-500 via-cyan-500 to-indigo-500">
                {report.score || 88}/100
              </span>
              <p className={`text-xs font-semibold uppercase tracking-wider mt-1 ${
                isDark ? 'text-slate-400' : 'text-slate-500'
              }`}>
                AI Readiness Score
              </p>
            </div>
          </div>

          {/* SECTION 1: BUSINESS OVERVIEW */}
          <div className="space-y-4">
            <h2 className={`text-xl font-bold flex items-center gap-2 border-l-4 border-indigo-500 pl-3 ${
              isDark ? 'text-white' : 'text-slate-900'
            }`}>
              <Building className="w-5 h-5 text-indigo-500" />
              1. Business Overview & Executive Summary
            </h2>
            <div className={`border rounded-2xl p-5 text-sm leading-relaxed ${
              isDark ? 'bg-slate-950/60 border-slate-800/80 text-slate-300' : 'bg-slate-50 border-slate-200 text-slate-700'
            }`}>
              {report.summary || 'Based on the provided details, your business has strong core potential in its local demographic. By optimizing digital customer touchpoints, setting up automated lead intake, and targeting high-intent local search queries, revenue can scale significantly.'}
            </div>
          </div>

          {/* SECTION 2: PROBLEMS & BOTTLENECKS */}
          <div className="space-y-4">
            <h2 className={`text-xl font-bold flex items-center gap-2 border-l-4 border-rose-500 pl-3 ${
              isDark ? 'text-white' : 'text-slate-900'
            }`}>
              <AlertTriangle className="w-5 h-5 text-rose-500" />
              2. Stated Problems & Identified Bottlenecks
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {report.problems && report.problems.length > 0 ? (
                report.problems.map((prob, idx) => (
                  <div key={idx} className={`border rounded-2xl p-5 space-y-2 ${
                    isDark ? 'bg-slate-950/60 border-slate-800/80' : 'bg-slate-50 border-slate-200'
                  }`}>
                    <div className="flex items-center justify-between">
                      <h3 className="text-sm font-bold text-rose-500">{prob.issue}</h3>
                      <span className="text-[10px] uppercase font-bold px-2 py-0.5 rounded bg-rose-500/10 text-rose-600 border border-rose-500/20">
                        {prob.impact || 'High Impact'}
                      </span>
                    </div>
                    <p className={`text-xs leading-relaxed ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>{prob.explanation}</p>
                  </div>
                ))
              ) : (
                <div className={`col-span-2 p-4 rounded-2xl text-xs border ${
                  isDark ? 'bg-slate-950/60 border-slate-800 text-slate-400' : 'bg-slate-50 border-slate-200 text-slate-600'
                }`}>
                  Main Challenge: {businessDetails?.businessProblems || 'Low digital conversion and offline dependency.'}
                </div>
              )}
            </div>
          </div>

          {/* SECTION 3: WEBSITE SUGGESTIONS */}
          <div className="space-y-4">
            <h2 className={`text-xl font-bold flex items-center gap-2 border-l-4 border-cyan-500 pl-3 ${
              isDark ? 'text-white' : 'text-slate-900'
            }`}>
              <Globe className="w-5 h-5 text-cyan-500" />
              3. High-Converting Website Suggestions
            </h2>
            <div className={`border rounded-2xl p-5 space-y-3 ${
              isDark ? 'bg-slate-950/60 border-slate-800/80' : 'bg-slate-50 border-slate-200'
            }`}>
              <p className={`text-xs font-semibold uppercase tracking-wider ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                Status: {businessDetails?.websiteRequirement || 'New Website Recommended'}
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {report.websiteSuggestions && report.websiteSuggestions.length > 0 ? (
                  report.websiteSuggestions.map((sug, idx) => (
                    <div key={idx} className={`flex items-start gap-3 p-3.5 rounded-xl border ${
                      isDark ? 'bg-slate-900/80 border-slate-800 text-slate-300' : 'bg-white border-slate-200 text-slate-700 shadow-sm'
                    }`}>
                      <CheckCircle2 className="w-4 h-4 text-cyan-500 shrink-0 mt-0.5" />
                      <p className="text-xs">{sug}</p>
                    </div>
                  ))
                ) : (
                  <p className="text-xs text-slate-500">Build a lightning-fast responsive website with sticky WhatsApp CTA, online scheduling, and social proof gallery.</p>
                )}
              </div>
            </div>
          </div>

          {/* SECTION 4: SEO STRATEGY */}
          <div className="space-y-4">
            <h2 className={`text-xl font-bold flex items-center gap-2 border-l-4 border-purple-500 pl-3 ${
              isDark ? 'text-white' : 'text-slate-900'
            }`}>
              <Search className="w-5 h-5 text-purple-500" />
              4. Hyper-Local SEO & Keyword Strategy
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {report.seoStrategy && report.seoStrategy.length > 0 ? (
                report.seoStrategy.map((seo, idx) => (
                  <div key={idx} className={`border rounded-2xl p-5 space-y-3 ${
                    isDark ? 'bg-slate-950/60 border-slate-800/80' : 'bg-slate-50 border-slate-200'
                  }`}>
                    <h3 className="text-sm font-bold text-purple-600 dark:text-purple-300">{seo.tactic}</h3>
                    <p className={`text-xs leading-relaxed ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>{seo.details}</p>
                    {seo.keywords && (
                      <div className="flex flex-wrap gap-1.5 pt-1">
                        {seo.keywords.map((kw, kIdx) => (
                          <span key={kIdx} className={`text-[11px] px-2.5 py-0.5 rounded-full border ${
                            isDark ? 'bg-purple-500/10 text-purple-300 border-purple-500/20' : 'bg-purple-50 text-purple-700 border-purple-200'
                          }`}>
                            #{kw}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                ))
              ) : (
                <div className={`col-span-2 p-4 rounded-2xl text-xs border ${
                  isDark ? 'bg-slate-950/60 border-slate-800 text-slate-400' : 'bg-slate-50 border-slate-200 text-slate-600'
                }`}>
                  Target local long-tail keywords in {businessDetails?.location} to dominate Google Maps 3-Pack rankings.
                </div>
              )}
            </div>
          </div>

          {/* SECTION 5: MARKETING PLAN */}
          <div className="space-y-4">
            <h2 className={`text-xl font-bold flex items-center gap-2 border-l-4 border-emerald-500 pl-3 ${
              isDark ? 'text-white' : 'text-slate-900'
            }`}>
              <Megaphone className="w-5 h-5 text-emerald-500" />
              5. Digital Marketing Plan & Channel Strategy
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {report.marketingPlan && report.marketingPlan.length > 0 ? (
                report.marketingPlan.map((mkt, idx) => (
                  <div key={idx} className={`border rounded-2xl p-5 space-y-2 ${
                    isDark ? 'bg-slate-950/60 border-slate-800/80' : 'bg-slate-50 border-slate-200'
                  }`}>
                    <div className="flex items-center justify-between">
                      <h3 className="text-sm font-bold text-emerald-600 dark:text-emerald-300">{mkt.channel}</h3>
                      <span className="text-[10px] font-semibold text-emerald-600 bg-emerald-500/10 px-2 py-0.5 rounded">
                        {mkt.expectedRoi || 'High ROI'}
                      </span>
                    </div>
                    <p className={`text-xs leading-relaxed ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>{mkt.strategy}</p>
                  </div>
                ))
              ) : (
                <div className={`col-span-2 p-4 rounded-2xl text-xs border ${
                  isDark ? 'bg-slate-950/60 border-slate-800 text-slate-400' : 'bg-slate-50 border-slate-200 text-slate-600'
                }`}>
                  Deploy targeted social media ad campaigns with automated WhatsApp lead routing.
                </div>
              )}
            </div>
          </div>

          {/* SECTION 6: GROWTH RECOMMENDATIONS */}
          <div className="space-y-4">
            <h2 className={`text-xl font-bold flex items-center gap-2 border-l-4 border-amber-500 pl-3 ${
              isDark ? 'text-white' : 'text-slate-900'
            }`}>
              <TrendingUp className="w-5 h-5 text-amber-500" />
              6. Top Growth Recommendations & Next Steps
            </h2>
            <div className="space-y-2.5">
              {report.growthRecommendations && report.growthRecommendations.length > 0 ? (
                report.growthRecommendations.map((rec, idx) => (
                  <div key={idx} className={`flex items-start gap-3 p-4 rounded-xl border ${
                    isDark ? 'bg-slate-950/80 border-slate-800/80 text-slate-200' : 'bg-slate-50 border-slate-200 text-slate-800'
                  }`}>
                    <div className="w-6 h-6 rounded-full bg-amber-500/20 text-amber-600 dark:text-amber-300 flex items-center justify-center text-xs font-bold shrink-0 mt-0.5">
                      {idx + 1}
                    </div>
                    <p className="text-sm">{rec}</p>
                  </div>
                ))
              ) : (
                <p className="text-xs text-slate-500">Implement responsive website, setup local SEO, and start daily customer messaging automation.</p>
              )}
            </div>
          </div>

          {/* Bottom Call to Action (Hidden on print) */}
          <div className={`pt-6 border-t flex flex-col sm:flex-row items-center justify-between gap-4 print:hidden ${
            isDark ? 'border-slate-800' : 'border-slate-200'
          }`}>
            <Link
              to="/analysis"
              className={`inline-flex items-center gap-2 px-5 py-3 rounded-xl border text-xs font-semibold transition-all w-full sm:w-auto justify-center ${
                isDark ? 'bg-slate-950 hover:bg-slate-800 text-slate-300 border-slate-800' : 'bg-slate-100 hover:bg-slate-200 text-slate-800 border-slate-300'
              }`}
            >
              <RefreshCw className="w-4 h-4 text-indigo-500" />
              Run Another Analysis
            </Link>

            <a
              href={`https://wa.me/919876543210?text=${whatsappMessage}`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-6 py-3.5 rounded-xl bg-[#25D366] hover:bg-[#20ba5a] text-white font-bold text-sm shadow-xl shadow-emerald-500/20 w-full sm:w-auto justify-center"
            >
              <MessageSquare className="w-4 h-4" />
              Consult Specialist to Execute Report Roadmap
            </a>
          </div>

        </div>

      </div>
    </div>
  );
}
